import type { LucideIcon } from "lucide-react";
import {
  Archive, ArrowLeftRight, BadgePercent, Banknote, Bell, Blocks, BookOpen, Brain,
  BriefcaseBusiness, Building2, Calendar, CalendarCheck2, ChartNoAxesCombined, ClipboardList,
  ContactRound, CreditCard, FileText, Files, FlaskConical, History, Inbox, KeyRound,
  Landmark, LayoutDashboard, MessageSquare, NotebookText, Package, Plane, Plug, Receipt,
  Scale, Settings, ShieldCheck, Sparkles, Telescope, TriangleAlert, Truck, Upload,
  User, UserCog, Users, WalletCards, WandSparkles, Workflow, Ellipsis,
} from "lucide-react";
import type { IconKey } from "@/core/navigation/registry";

export const iconRegistry: Record<IconKey, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  sparkles: Sparkles,
  inbox: Inbox,
  building: Building2,
  truck: Truck,
  contact: ContactRound,
  package: Package,
  briefcase: BriefcaseBusiness,
  users: Users,
  plane: Plane,
  clipboard: ClipboardList,
  receipt: Receipt,
  "credit-card": CreditCard,
  wallet: WalletCards,
  landmark: Landmark,
  "arrow-left-right": ArrowLeftRight,
  files: Files,
  "file-text": FileText,
  archive: Archive,
  chart: ChartNoAxesCombined,
  notebook: NotebookText,
  telescope: Telescope,
  flask: FlaskConical,
  brain: Brain,
  shield: ShieldCheck,
  "triangle-alert": TriangleAlert,
  history: History,
  "calendar-check": CalendarCheck2,
  scale: Scale,
  calendar: Calendar,
  "book-open": BookOpen,
  "badge-percent": BadgePercent,
  workflow: Workflow,
  wand: WandSparkles,
  bell: Bell,
  plug: Plug,
  "user-cog": UserCog,
  "key-round": KeyRound,
  blocks: Blocks,
  settings: Settings,
  "message-square": MessageSquare,
  upload: Upload,
  user: User,
  banknote: Banknote,
  ellipsis: Ellipsis,
};
